### ISSUE TITLE
保存资源busy or locked，导致进程退出

### ISSUE THREAD

**Issue by lincong1987** [Chatie/wechaty-puppet-puppeteer#59]
这个问题不太多见，但是每次出现便会使进程退出。

code：
```javascript
await file.toFile(`${dir_path}${file_path}${file_name}`, true).catch((e) => {
    logger.info(`保存文件失败，${dir_path}${file_path}${file_name}`)
    logger.error(e)
    file_path = "";
});
```
logs:
```

2018-12-17 12:39:41.438 { [Error: EBUSY: resource busy or locked, open 'C:\assets\image\2018-12-17\528548419131008142.jpg']
  errno: -4082,
  code: 'EBUSY',
  syscall: 'open',
  path:
   'C:\\assets\\image\\2018-12-17\\528548419131008142.jpg' }

2018-12-17 12:39:41.517 Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at WriteStream.Writable.write (_stream_writable.js:294:11)
    at IncomingMessage.ondata (_stream_readable.js:666:20)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at writeOrBuffer (_stream_writable.js:394:5)
    at WriteStream.Writable.write (_stream_writable.js:294:11)
    at IncomingMessage.ondata (_stream_readable.js:666:20)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.EventEmitter.emit (domain.js:442:20)
    at IncomingMessage.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

2018-12-17 12:39:41.568 PID:33916 npm 1 exit!
```

**Comment by huan** [comment]
This issue is related to wechaty, please file an issue at <https://github.com/huan/file-box> if you could provide any minimum reproducible code snip.
