### ISSUE TITLE
TypeError: MyPuppet is not a constructor

### ISSUE THREAD

**Issue by suntong** [Chatie/wechaty-puppet-puppeteer#60]
I'm getting the `TypeError: MyPuppet is not a constructor` error when running wechaty after upgrading it:

cd wechaty-getting-started/examples

$ git pull
Already up to date.
Current branch master is up to date.

```
$ WECHATY_PUPPET=puppeteer node starter-bot.js 
00:56:00 INFO PuppetManager install(puppeteer@latest) done
TypeError: MyPuppet is not a constructor
    at Function.<anonymous> (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:58:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:4:58)
00:56:00 ERR Wechaty start() exception: MyPuppet is not a constructor
TypeError: MyPuppet is not a constructor
    at Function.<anonymous> (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:58:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:4:58)
```

Here is more info:

```
$ node -v
v11.5.0

$ npm -v
6.5.0

$ npm -g outdated | wc
      0       0       0

`$ npm outdated | wc 
      0       0       0

$ lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
``

### Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly WECHATY_PUPPET=puppeteer node starter-bot.js
01:03:52 SILL Config WECHATY_LOG set level to silly
01:03:52 INFO Config registering process.on("unhandledRejection") for development/debug
01:03:52 VERB Config constructor()
01:03:53 SILL Accessory #0<Wechaty> constructor()
01:03:53 VERB Wechaty contructor()
01:03:53 VERB StateSwitch constructor(name=Wechaty)
01:03:53 VERB StateSwitch constructor(name=WechatyReady)
01:03:53 VERB Wechaty on(scan, function) registered
01:03:53 VERB Wechaty onFunction(scan)
01:03:53 VERB Wechaty on(login, function) registered
01:03:53 VERB Wechaty onFunction(login)
01:03:53 VERB Wechaty on(logout, function) registered
01:03:53 VERB Wechaty onFunction(logout)
01:03:53 VERB Wechaty on(message, function) registered
01:03:53 VERB Wechaty onFunction(message)
01:03:53 SILL Wechaty version() form development environment is not availble: ENOENT: no such file or directory, stat '/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/.git'
01:03:53 INFO Wechaty <puppeteer> start() v0.22.6 is starting...
01:03:53 VERB Wechaty puppet: undefined
01:03:53 VERB Wechaty profile: undefined
01:03:53 VERB Wechaty id: cjpz261cu0000xtfu5a8r7fzu
01:03:53 SILL StateSwitch <Wechaty> on() is false
01:03:53 SILL StateSwitch <WechatyReady> off() is true
01:03:53 VERB StateSwitch <WechatyReady> off(true) <- (true)
01:03:53 SILL StateSwitch <Wechaty> on() is false
01:03:53 VERB StateSwitch <Wechaty> on(pending) <- (false)
01:03:53 VERB MemoryCard constructor(undefined)
01:03:53 VERB MemoryCard getStorage() for storage type: N/A
01:03:53 VERB MemoryCard load() from storage: N/A
01:03:53 VERB MemoryCard load() no storage
01:03:53 VERB Wechaty initPuppet() 
01:03:53 VERB MemoryCard multiplex(puppet)
01:03:53 VERB MemoryCard static multiplex(MemoryCard<>, puppet)
01:03:53 VERB MemoryCard constructor({"multiplex":{"name":"puppet","parent":{"payload":{},"multiplexNameList":[]}}})
01:03:53 VERB PuppetManager resolve({wechaty: Wechaty#cjpz261cu0000xtfu5a8r7fzu<>(), puppet: puppeteer, puppetOptions: undefined})
01:03:53 VERB PuppetManager resolveName(puppeteer)
01:03:53 VERB PuppetManager checkModule(puppeteer)
01:03:53 SILL PuppetManager checkModule() puppeteer installed version 1.11.0 NOT satisfied range undefined
01:03:53 INFO PuppetManager install(puppeteer@latest) please wait ...
npm: 
> puppeteer@1.11.0 install /path/to/wechaty-getting-started/examples/node_modules/wechaty/node_modules/puppeteer
> node install.js


npm: 

npm: Chromium downloaded to /path/to/wechaty-getting-started/examples/node_modules/wechaty/node_modules/puppeteer/.local-chromium/linux-609904

npm: + puppeteer@1.11.0
updated 1 package and audited 64 packages in 23.95s

npm: found 0 vulnerabilities


01:04:18 INFO PuppetManager install(puppeteer@latest) done
TypeError: MyPuppet is not a constructor
    at Function.<anonymous> (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:58:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:4:58)
01:04:18 ERR Wechaty start() exception: MyPuppet is not a constructor
TypeError: MyPuppet is not a constructor
    at Function.<anonymous> (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:58:34)
    at Generator.next (<anonymous>)
    at fulfilled (/path/to/wechaty-getting-started/examples/node_modules/wechaty/dist/src/puppet-manager.js:4:58)
```

</details>

**Comment by huan** [comment]
Yes, you should use `WECHATY_PUPPET=wechaty-puppet-puppeteer`
