### ISSUE TITLE
偶现 Error: connect ETIMEDOUT，导致进程退出

### ISSUE THREAD

**Issue by lincong1987** [Chatie/wechaty-puppet-puppeteer#61]
这个问题出现的概率不大，但出现必然导致进程退出。
logs:
```
2018-12-22 16:37:03.690 { Error: connect ETIMEDOUT 223.166.152.108:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '223.166.152.108',
  port: 80 }

Error: connect ETIMEDOUT 223.166.152.108:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)

2018-12-22 16:37:03.744 PID:16356 npm 1 exit!
```

**Comment by zzc-tongji** [comment]
是的，使用 file-box 题取文件时尤其如此，详见 #124 。
