### ISSUE TITLE
wechaty 有人退群的时候报错

### ISSUE THREAD

**Issue by yuqingc** [Chatie/wechaty-puppet-puppeteer#88]
```
error: no id
    at Firer.<anonymous> (/.../node_modules/wechaty-puppet-puppeteer/src/firer.ts:349:13)
    at Generator.next (<anonymous>)
    at fulfilled (/.../node_modules/wechaty-puppet-puppeteer/dist/src/firer.js:22:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
报错是这里的[代码](https://github.com/Chatie/wechaty-puppet-puppeteer/blob/master/src/firer.ts#L348) 报出的，而且我看注释也写了 fixme。啥时候可以修复呀。

**Comment by yuqingc** [comment]
@huan

**Comment by huan** [comment]
It would  be great if you can provide:
1. the reproduce-able code
1. the Pull Request that could fix this issue.

Otherwise, we will not be able to look into it very soon because we have very limited resource to maintain this module.

**Comment by blachworld** [comment]
我也遇到了 但是暂时没有定位出来 请问 @yuqingc 你解决这个问题了吗
